In [7]:
#Setup

#Run if on a clean python install.
#! pip install numpy

#Load dependencies
import numpy as np

In [ ]:
#Q1.

Yes

In [31]:
#Q2.


#a.
x=1-(0.16+0.16+0.22+0.26)
print(f"x=",x)
#x=0.2

#The property I am using is that the sum of each row of a stochastic matrix is 1.
#This holds mathematically because each row contains the probability of every possible state change from n to n+1.
#Since probabilities need to sum to 1, and each row contains all probabilities of an event, each row must sum to 1.


#b.
#Initial distribution states
pi0=np.array([0.13,0.24,0.32,0.28,0.03])

#Write up P
P=np.array([[0.21,0.07,0.15,0.11,0.46],[0,1,0,0,0],[0.16,0.16,0.22,0.2,0.26],[0,0,0,1,0],[0.21,0.27,0.18,0.24,0.1]])
print(P)

#Raising a stochastic matrix to the x power gives the distribution of states after x generations
#First generation is P^1, so pi*P
print(f"The first generation is",np.matmul(pi0,P))
#Second generation
print(f"The second generation is",np.matmul(pi0,np.linalg.matrix_power(P,2)))
#Third generation
print(f"The third generation is",np.matmul(pi0,np.linalg.matrix_power(P,3)))

#Over time, the distribution tends towards B and D.  This makes sense, as B and D are absorbing states.


#c.
P2=np.array([[0.21,0.15,0.46,0.07,0.11],[0.16,0.22,0.26,0.16,0.2],[0.21,0.18,0.1,0.27,0.24],[0,0,0,1,0],[0,0,0,0,1]])
print(P2)

#R is the upper right corner of P, so P14 through P35
R=np.array([[0.07,0.11],[0.16,0.2],[0.27,0.24]])
print(f"R=",R)

#Q is the upper left corner of P, so P11 through P33
Q=np.array([[0.21,0.15,0.46],[0.16,0.22,0.26],[0.21,0.18,0.1]])
print(f"Q=",Q)


#d.
#So I need to calculate N, which is (I-Q)^-1.
#I is the identity matrix
#Q is from earlier and is all states from the matrix that are transient to transient
I=np.eye(3)
N=np.linalg.matrix_power((I-Q),-1)
print(f"N=",N)


#e.
#So I need to calculate M, which is the sum of each row of N
M=np.array([sum(N[0]),sum(N[1]),sum(N[2])])
print(f"M=",M)


#f.
#So I need to calculate B, which is N dot R.  R is all states from the matrix that are transient to absorbing
B=np.matmul(N,R)
print(f"B=",B)

x= 0.19999999999999996
[[0.21 0.07 0.15 0.11 0.46]
 [0.   1.   0.   0.   0.  ]
 [0.16 0.16 0.22 0.2  0.26]
 [0.   0.   0.   1.   0.  ]
 [0.21 0.27 0.18 0.24 0.1 ]]
The first generation is [0.0848 0.3084 0.0953 0.3655 0.146 ]
The second generation is [0.063716 0.369004 0.059966 0.428928 0.078386]
The third generation is [0.03943598 0.4042229  0.0368594  0.4667426  0.05273912]
[[0.21 0.15 0.46 0.07 0.11]
 [0.16 0.22 0.26 0.16 0.2 ]
 [0.21 0.18 0.1  0.27 0.24]
 [0.   0.   0.   1.   0.  ]
 [0.   0.   0.   0.   1.  ]]
R= [[0.07 0.11]
 [0.16 0.2 ]
 [0.27 0.24]]
Q= [[0.21 0.15 0.46]
 [0.16 0.22 0.26]
 [0.21 0.18 0.1 ]]
N= [[1.64119212 0.54556112 0.99643807]
 [0.49746757 1.53899334 0.69885928]
 [0.48243834 0.43509626 1.48338518]]
M= [3.18319131 2.7353202  2.40091979]
B= [[0.47121151 0.52878849]
 [0.46975367 0.53024633]
 [0.50390009 0.49609991]]
